name: Publish

on:
  push:
    tags:
      - v*

run-name: Publish ${{ github.ref_name }}

permissions:
  contents: write
  id-token: write
  packages: write
  pages: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: latest
      - run: pnpm install
      - run: pnpm build
      - uses: actions/setup-node@v4
        with:
          registry-url: https://npm.pkg.github.com
      - run: pnpm publish --access public --no-git-checks --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org
      - run: pnpm publish --access public --no-git-checks --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      - run: pnpm pack --pack-gzip-level 9
      - run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.DEPLOY_KEY_PRIVATE }}'
          echo '${{ vars.DEPLOY_KEY_PUBLIC }}' > '${{ runner.temp }}/DEPLOY_KEY_PUBLIC.pub'
          ssh-keygen -Y sign -f '${{ runner.temp }}/DEPLOY_KEY_PUBLIC.pub' -n file rafters.ts-*.tgz
          ssh-keygen -Y verify -f ./.github/authorized_keys -I '41898282+github-actions[bot]@users.noreply.github.com' -n file -s rafters.ts-*.tgz.sig < rafters.ts-*.tgz
      - run: gh release upload ${{ github.ref_name }} rafters.ts-*.tgz rafters.ts-*.tgz.sig
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-storybook:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy-storybook.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: latest
      - run: pnpm install
      - id: deploy-storybook
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          path: dist
