name: Publish Storybook

on:
  push:
  workflow_dispatch:
    inputs:
      force:
        description: Force publish
        type: boolean
        default: false
        required: false

run-name: Publish Storybook to Chromatic

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  changed-files:
    name: Detect changed files
    runs-on: ubuntu-latest
    outputs:
      any-changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            src/**
            .storybook/**

  storybook:
    name: Publish Storybook
    runs-on: ubuntu-latest
    needs:
      - changed-files
    if: ${{ inputs.force || needs.changed-files.outputs.any-changed == 'true' }}
    environment:
      name: chromatic
      url: ${{ steps.chromatic.outputs.buildUrl }}
    steps:
      - uses: actions/checkout@v4
      - id: tool-versions
        run: |
          echo "node-version=$(./scripts/tool-versions.sh nodejs)" >> $GITHUB_OUTPUT
          echo "pnpm-version=$(./scripts/tool-versions.sh pnpm)" >> $GITHUB_OUTPUT
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ steps.tool-versions.outputs.pnpm-version }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.tool-versions.outputs.node-version }}
          cache: pnpm
      - run: pnpm install
      - id: chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: main
          skip: dependabot/**
          token: ${{ secrets.GITHUB_TOKEN }}
